name: Build and Push Docker Image on Version Change

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get latest image tag from GHCR
      id: get_ghcr_tag
      run: |
        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer ${{ secrets.GHCR_PAT }}" \
          https://api.github.com/user/packages/container/beszel-agent/versions)
        if [ "$RESPONSE" -eq 404 ]; then
          echo "Package not found, proceeding with build."
          echo "::set-output name=ghcr_tag::not_found"
        else
          GHCR_TAG=$(curl -s -H "Authorization: Bearer ${{ secrets.GHCR_PAT }}" \
            https://api.github.com/user/packages/container/beszel-agent/versions \
            | jq -r '.[0].metadata.container.tags[0]')
          echo "GHCR tag: $GHCR_TAG"
          echo "::set-output name=ghcr_tag::$GHCR_TAG"
        fi

    - name: Get latest tag from remote repo
      id: get_remote_tag
      run: |
        REMOTE_TAG=$(curl -s https://api.github.com/repos/henrygd/beszel/tags | jq -r '.[0].name')
        echo "Remote tag: $REMOTE_TAG"
        echo "::set-output name=remote_tag::$REMOTE_TAG"

    - name: Strip 'v' from remote tag
      id: strip_v
      run: |
        STRIPPED_TAG=${{ steps.get_remote_tag.outputs.remote_tag }}
        STRIPPED_TAG=${STRIPPED_TAG#v}
        echo "Stripped tag: $STRIPPED_TAG"
        echo "::set-output name=stripped_tag::$STRIPPED_TAG"

    - name: Compare tags
      id: compare_tags
      run: |
        if [ "${{ steps.get_ghcr_tag.outputs.ghcr_tag }}" != "${{ steps.strip_v.outputs.stripped_tag }}" ]; then
          echo "Tags differ, building new image."
          echo "::set-output name=build::true"
        else
          echo "Tags are the same, no build needed."
          echo "::set-output name=build::false"
        fi

    - name: Build and push Docker image
      if: steps.compare_tags.outputs.build == 'true'
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/beszel-agent:latest
          ghcr.io/${{ github.repository_owner }}/beszel-agent:${{ steps.strip_v.outputs.stripped_tag }}
        build-args: |
          VERSION=${{ steps.strip_v.outputs.stripped_tag }}
